target: &target 'leadFunder' # Variable to predict

data:  # make_dataset.py
    gtr:
        usecols: ['id', 'abstractText', *target]
        nrows : 1000
        min_chars : 140
        min_length : 3

features:  # build_features.py
  w2v:
  # Passed to gensim.models.Word2Vec
  # See: https://radimrehurek.com/gensim/models/word2vec.html
    workers: 1
    size: 50
    window: 10
    min_count: 2
    iter: 20
    seed: 1

split:  # train_test_split.py
  random_state: 0
  shuffle: True
  train_size: 0.8

model:  # train_model.py
  target: *target
  grid:
    param_grid: {
           'tfidf__max_df': [0.8, 0.9, 1.0],
           'tfidf__min_df': [1, 2, 3],
           'logr__C': [0.1, 1, 10, 100],
           'logr__random_state': [1],
           }
    cv: 3
    verbose: 5
    n_jobs: 1
  best:
    param_grid: {
           'tfidf__max_df': [0.8],
           'tfidf__min_df': [1],
           'logr__C': [100],
           'logr__random_state': [1],
           }
    cv: 3
    verbose: 5
    n_jobs: 1

evaluate:  # evaluate.py
  target: *target
