target: &target 'leadFunder' # Variable to predict

data:  # make_dataset.py
    gtr:
        usecols: ['id', 'abstractText', *target]
        nrows : !!null
        min_chars : 140
        min_length : 3

split:  # train_test_split.py
  random_state: 0
  shuffle: True
  train_size: 0.8

model:  # train_model.py
  target: *target
  grid:
    param_grid: {
           'tfidf__max_df': [0.8, 0.9, 1.0],
           'tfidf__min_df': [1, 2, 3],
           'logr__C': [0.1, 1, 10, 100],
           }
    cv: 3
    verbose: 5
    n_jobs: 3
  best:
    param_grid: {
           'tfidf__max_df': [0.8],
           'tfidf__min_df': [1],
           'logr__C': [100],
           }
    cv: 3
    verbose: 5
    n_jobs: 1

evaluate:  # evaluate.py
  target: *target
